# This is a basic workflow to help you get started with Actions

name: caffeine

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file caffeine/pom.xml
      

    - name: Run a multi-line script
      run: |
        ls -l caffeine
        java -jar caffeine/target/demo-0.0.1-SNAPSHOT.jar -Xms128m -Xmx1024m -XX:MaxPermSize=512m &
        sleep 10
        vmstat 1 5
