# This is a basic workflow to help you get started with Actions

name: springboot

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:




# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file springboot/pom.xml
      

    - name: Run a multi-line script
      run: |
        ls -l
        ls -l springboot
        java -jar springboot/target/demo-0.0.1-SNAPSHOT.jar &
        sleep 10
        curl http://127.0.0.1:8080/
        sudo apt-get install -y apache2-utils
        ab -c 100 -n 1000000  http://127.0.0.1:8080/
        top > top.txt
        cat top
